### ISSUE TITLE
What is the usage of val_dataset

### ISSUE THREAD

**Issue by SYH0568** [ChunML/ssd-tf2#17]
I found that you split data into two part when training, but I couldn't found where did you use the val_dataset. Whether can I not to split the data?
This is the part of cord I am confused?
        self.train_ids = self.ids[:int(len(self.ids) * 0.75)]
        self.val_ids = self.ids[int(len(self.ids) * 0.75):]

**Comment by ChunML** [comment]
Of course, if you have a separate validation dataset, you can modify the code to use data from that.
